# Generated by Django 2.2.16 on 2020-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_form',
            name='pregnancy',
            field=models.CharField(blank=True, default='No', max_length=100, null=True),
        ),
    ]
